---
gitlab_mode: connect
gitlab_url: https://git.divband.ir
gitlab_package_name: gitlab-ee
gitlab_external_url: "{{ gitlab_url }}"
gitlab_terraform_dir: "{{ playbook_dir }}/../../gitlab/terraform"
gitlab_run_terraform: false
gitlab_terraform_plan_file: tfplan
gitlab_root_password: "{{ vault_gitlab_root_password | default(omit) }}"
