---
external_secrets_manifest_url: https://raw.githubusercontent.com/external-secrets/external-secrets/v0.10.4/deploy/crds/bundle.yaml
external_secrets_namespace: external-secrets
external_secrets_store_name: divband-tenant-secrets
external_secrets_provider: vault
external_secrets_vault_server: https://vault.divband.ir
external_secrets_vault_path: secret
external_secrets_vault_version: v2
external_secrets_vault_auth_secret_name: vault-token
external_secrets_vault_auth_secret_key: token
