---
divband_timezone: UTC
common_base_packages:
  - ca-certificates
  - curl
  - gnupg
  - jq
  - openssh-server
  - python3
  - python3-apt
  - rsync
  - ufw
common_ssh_port: 22
common_ssh_password_authentication: false
common_ssh_permit_root_login: false
common_firewall_default_allow_outgoing: true
common_firewall_allowed_tcp_ports:
  - "{{ common_ssh_port }}"
  - 80
  - 443
common_firewall_additional_rules: []
divband_admin_users: []
